### ISSUE TITLE
Feature: Support for Multi-Mesh Single DFF with Multiple BON

### ISSUE THREAD

**Issue by dreamsyntax** [Psycrow101/Blender-3D-STH-Mtn-plugin#3]
Shadow the Hedgehog has some models with multi-mesh that use multiple bon files.
`DEVILDOOM.DFF` is one such model.

It uses four BON file with one model.
`DEVILDOOM.BON`
`DEVILDOOMBALL.BON`
`DEVILDOOMWINGL.BON`
`DEVILDOOMWINGR.BON`

This model can not be imported properly unless using your multi-mesh DragonFF branch.

I labeled the meshes for easier identification.
![image](https://github.com/Psycrow101/Blender-3D-STH-Mtn-plugin/assets/14857235/f5bd2771-3b45-4361-8a73-fba1dea9f9fa)

Importing the `DEVILDOOMBALL.BON` properly labels ball bones, but messes up rest of the model.
`DevilDoomBall_ballfly.MTN` will work properly for this piece of the model when applied.

![image](https://github.com/Psycrow101/Blender-3D-STH-Mtn-plugin/assets/14857235/5606701e-3534-4974-b389-6409e43012a0)

Importing `DEVILDOOM.BON` and applying `DevilDoom_start.MTN` only moves the eye on the model, though you can see the bones move as expected but the model is detached. Presumably its only attaching to EYE_F mesh?

I'm not really sure where to begin with this. Maybe deleting meshes/merging them and re-combing as multiple objects in an external editor?
[DevilDoomOne.zip](https://github.com/Psycrow101/Blender-3D-STH-Mtn-plugin/files/11638191/DevilDoomOne.zip)
[DEVILDOOMMTN.zip](https://github.com/Psycrow101/Blender-3D-STH-Mtn-plugin/files/11638194/DEVILDOOMMTN.zip)
[DevilDoomONE_MultiMeshDragonFFImported_NO_BON_APPLIED_BLEND_FILE.zip](https://github.com/Psycrow101/Blender-3D-STH-Mtn-plugin/files/11638256/DevilDoomONE_MultiMeshDragonFFImported_NO_BON_APPLIED.zip)

**Comment by Psycrow101** [comment]
This is a problem with the multi-mesh branch. I updated [DragonFF](https://github.com/Psycrow101/DragonFF/commit/483b608e4338109abe1a93a287c6c1cf512d6297) to partially fix the problem. After importing the model, try the following steps:

1. Apply Copy Transform constraints to all meshes.
![image](https://github.com/Psycrow101/Blender-3D-STH-Mtn-plugin/assets/31922454/e682032d-fb7b-4faf-b84f-467d87659642)
2. Import DEVILDOOM.BON
3. Import MTN

**Comment by dreamsyntax** [comment]
I've tried your new version in this branch.
https://github.com/Parik27/DragonFF/compare/master...Psycrow101:DragonFF:multi-mesh

Probably unsurprisingly it breaks applying bon to non-multi mesh.
Works for this model though. I'll switch back and forth as needed. Thank you!

**Comment by Psycrow101** [comment]
This issue should be fixed with the latest version of DragonFF multi-mesh

**Comment by dreamsyntax** [comment]
I'll verify

**Comment by dreamsyntax** [comment]
It seems good, but I'm confused on something...
I only imported DEVILDOOM.DFF and DEVILDOOM.BON; Yet I have the hierarchy from the other two .bon
Does your plugin automatically pull in the other .bon?
![image](https://github.com/Psycrow101/Blender-3D-STH-Mtn-plugin/assets/14857235/00e2ba31-bdc1-4368-8265-b5213568e58a)

![image](https://github.com/Psycrow101/Blender-3D-STH-Mtn-plugin/assets/14857235/5e4286fb-4273-45ec-bbc4-92e8df57dc29)

**Comment by Psycrow101** [comment]
DEVILDOOM.BON already contains a hierarchy of other BONs. I suspect that Sega created multiple BONs to separate the movement of different segments and reduce ROM memory usage or something like that.

**Comment by dreamsyntax** [comment]
Interesting, alright thank you for all your work on this!! Really appreciate it.
