### ISSUE TITLE
Feature: Bulk Import / Save

### ISSUE THREAD

**Issue by dreamsyntax** [Psycrow101/Blender-3D-STH-Mtn-plugin#4]
Not sure how feasible this would be:

In 3DSMax the Sonic Heroes animation had the option to target a folder rather than individual .mtn; This feature would be similar.
https://github.com/Shadowth117/Renderware-.anm-IO-Tool/blob/6ce0c1c4b8adf3f3be428032080cae681b95da42/Sonic%20Heroes%20ANM%20IO%20Tool%20v1.ms#L662C23-L662C28

Then, you would be able to change on the fly which animation to apply using a pop-up window.

Ideally (thought this does not exist as far as I'm aware) there would be a bulk .blend save action as well.

Example:
Given SN.DFF, SN.BON, and a folder containing MTNs from the MTP:
![image](https://github.com/Psycrow101/Blender-3D-STH-Mtn-plugin/assets/14857235/392535a3-020f-4dec-9383-13b1b6455800)

*Assumes the user already has imported the DFF, and applied the .bon
1. Blender -> Import Shadow the Hedgehog animation (folder), selecting the above folder
2. An output folder picker is provided
3. sn_atc.MTN is loaded, applied, then sn_atc.blend is saved to the output folder
4. sn_atc.MTN is unloaded / the state before step 3 is restored.
5. sn_atc_dash.MTN  is loaded applied, then sn_atc_dash.blend is saved to the output folder
6. repeat/looping steps 3-5 for all remaining .MTN in the folder.

**Comment by Psycrow101** [comment]
It's possible to do this, but it's better to implement it as a separate extension from the import/export

**Comment by dreamsyntax** [comment]
> It's possible to do this, but it's better to implement it as a separate extension from the import/export

Got it, I'll look into this then. Thanks.
