### ISSUE TITLE
Unable to Export all Animations as one file due to unlinked actions 

### ISSUE THREAD

**Issue by dreamsyntax** [Psycrow101/Blender-3D-STH-Mtn-plugin#6]
It seems adding all the MTNs to the action editor wont result in them populating on export to other formats such as GLB.
If you manually view each in the action editor, it will show them in the export however the animations themselves will be completely broken. -- Update, this is because the actions are unlinked: https://github.com/Psycrow101/Blender-3D-STH-Mtn-plugin/issues/6#issuecomment-1805117670

I'm assuming the intention was to have all the animations embedded in one file, like apicula
apicula example:
![image](https://github.com/Psycrow101/Blender-3D-STH-Mtn-plugin/assets/14857235/88be80f9-b800-45f1-af46-9d290c379a95)

However it does not seem to operate that way.

~~To save on space per glb it would be better to only import one MTN, like before this commit https://github.com/Psycrow101/Blender-3D-STH-Mtn-plugin/commit/713979fbfc8ceee4f0671108fde5fe5fabdf65da~~ There is no reason to change this, since the end filesize stays the same since those actions do not get exported as they are not linked.

~~I made a temp branch here
https://github.com/Psycrow101/Blender-3D-STH-Mtn-plugin/commit/93c706f21a705916c9d9463c2bf9d2c524434228
But its probably based on an old version.~~

**Comment by dreamsyntax** [comment]
........
I think I just realized the issue had nothing to do with the addon:

![image](https://github.com/Psycrow101/Blender-3D-STH-Mtn-plugin/assets/14857235/d329eb7c-3cf7-4f02-8ad5-7b6868aab44d)

My export settings were wrong in my script, I need to account for this.

**Comment by dreamsyntax** [comment]
Seems I posted too soon, while the actions are in the blender hierarchy, they are in an unlinked state so they will not export.
![image](https://github.com/Psycrow101/Blender-3D-STH-Mtn-plugin/assets/14857235/587304f8-d8d3-4da1-a10e-76c4a9646575)

Using Cleanup shows this, and results in only the two actions that we see in the final export even with Bake All Object Animations on.


For now I'm just exporting each MTN separately, like this:
https://github.com/ShadowTheHedgehogHacking/blender-import-pipeline/blob/main/mtn-dff-bon-glb-separate-per-mtn.py

**Comment by dreamsyntax** [comment]
For example, this is what I'm looking for (all mtns in one glb).
![image](https://github.com/Psycrow101/Blender-3D-STH-Mtn-plugin/assets/14857235/567febb0-28ae-47f2-92ae-94409097141c)

I accomplished this with
```python
# Activate all actions for the armature
if bpy.context.object.animation_data:
    for track in bpy.context.object.animation_data.nla_tracks:
        bpy.context.object.animation_data.nla_tracks.remove(track)
        
# Create a new NLA track for each action
for action in bpy.data.actions:
    track = bpy.context.object.animation_data.nla_tracks.new()
    track.strips.new(action.name, 0, action)
```

However this breaks all baked tracks.

**Comment by Psycrow101** [comment]
@dreamsyntax try this. There will be a new option **Create NLA track** when importing animations.
[io_scene_sth_mtn.zip](https://github.com/Psycrow101/Blender-3D-STH-Mtn-plugin/files/13327816/io_scene_sth_mtn.zip)

**Comment by dreamsyntax** [comment]
> @dreamsyntax try this. There will be a new option **Create NLA track** when importing animations. [io_scene_sth_mtn.zip](https://github.com/Psycrow101/Blender-3D-STH-Mtn-plugin/files/13327816/io_scene_sth_mtn.zip)

Using this still seems to export only the *final* animation and baked animation. If left by itself.

Using this in combination [with my updated script, ](https://github.com/ShadowTheHedgehogHacking/blender-import-pipeline/blob/main/mtn-dff-bon-glb-aio-mtns.py) even stripping out the prior NLA action removes (tried both ways) , results in the non-baked animation bones moving as expected, but any baked animation will simply be the final animation that was imported in Blender, in this case the 
![image](https://github.com/Psycrow101/Blender-3D-STH-Mtn-plugin/assets/14857235/c05e61f1-fe5f-4491-9568-f07ca72f4eec)

`DevilDoom_wingguard.MTN`

![image](https://github.com/Psycrow101/Blender-3D-STH-Mtn-plugin/assets/14857235/42269838-aaa7-4d69-ba87-6a663d3f53b3)

In this video you can see the `DevilDoom_bodypsycho0.MTN` non baked move the bones as expected, but the baked version plays the wing_guard anim instead.
https://github.com/Psycrow101/Blender-3D-STH-Mtn-plugin/assets/14857235/2eaeec20-946f-4ab0-ad74-51407b773670


Using my old script (with the NLA recreation) takes 15mins and results in the same as the above, however without the original bone tracks.

**Comment by Psycrow101** [comment]
@dreamsyntax try removing the BON armature before exporting
```python
for o in bpy.context.scene.objects:
    if o.get("bon_model_name") is not None:
        bpy.data.objects.remove(o, do_unlink=True)
```

**Comment by dreamsyntax** [comment]
I'll give this a try when I figure out whats going on with my blender install.
```
Python: Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
ModuleNotFoundError: No module named 'DragonFF'
```
Also tried `DragonFF_multi_mesh` per blender docs, but I find it weird it was working before. Note I started getting this before even upgrading to the latest addon and 4.0, so its probably a mistake on my end.

In any case I'll report back once I've tested your suggestion.

**Comment by dreamsyntax** [comment]
> @dreamsyntax try removing the BON armature before exporting
> 
> ```python
> for o in bpy.context.scene.objects:
>     if o.get("bon_model_name") is not None:
>         bpy.data.objects.remove(o, do_unlink=True)
> ```

Finally fixed my blender; Unfortunately no, this results in the same output as my last test, though 1kb less in size. (although this could be a consequence of using blender 4.0.2)

![image](https://github.com/Psycrow101/Blender-3D-STH-Mtn-plugin/assets/14857235/624b093f-1ea2-46ab-abc4-21b44d5b163d)

![image](https://github.com/Psycrow101/Blender-3D-STH-Mtn-plugin/assets/14857235/0fb7850d-10a7-4070-92bd-c6cd5b7faa93)

Relevant change:
```python
for mtn in mtns:
    input_path = os.path.join(mtn_directory, mtn)
        
    ### MTN Import ###

    bpy.ops.object.select_all(action='DESELECT')

    # Start the search from the root level collections
    for collection in bpy.data.collections:
        bon_root_armature = find_bon_root_armature(collection)
        if bon_root_armature:
            # Set the armature as the active object
            bpy.context.view_layer.objects.active = bon_root_armature

            # Select the armature
            bon_root_armature.select_set(True)
            break

    import_sth_mtn.load(bpy.context, input_path, bake_action, True)
    
output_path = os.path.join(mtn_output, "AIO_DevilDoomUnlink" + '.glb')

for o in bpy.context.scene.objects:
    if o.get("DevilDoom.bon") is not None:
        bpy.data.objects.remove(o, do_unlink=True)

bpy.ops.export_scene.gltf(
    filepath=output_path,
    export_animations=True,
    export_materials='EXPORT'
)
```

**Comment by Psycrow101** [comment]
@dreamsyntax
```python
if o.get("DevilDoom.bon") is not None:
```
There is no need to specify the BON name instead of "bon_model_name". "bon model_name" is a custom property that is present in all imported BON objects. 

So use this condition as is
```python
if o.get("bon_model_name") is not None:
```
Or for your specific case:
```python
bpy.data.objects.remove(bpy.context.scene.objects['DevilDoom.bon'], do_unlink=True)
```

I tested the export with these parameters:
```python
bpy.ops.export_scene.gltf(
    filepath=output_path,
    export_animations=True,
    export_animation_mode='NLA_TRACKS',
    export_materials='EXPORT'
)
```

**Comment by Psycrow101** [comment]
There is also no need to create NLA tracks. This code will work for the version of the addon without NLA (main branch):

```python
import bpy

import os
from DragonFF.ops import dff_importer
from io_scene_sth_mtn import import_sth_mtn

def cleanup():
    bpy.ops.object.select_all(action='SELECT')
    bpy.ops.object.delete()
    for collection in bpy.data.collections:
        bpy.context.scene.collection.children.unlink(collection)
        bpy.data.collections.remove(collection)
    bpy.ops.outliner.orphans_purge(do_local_ids=True, do_linked_ids=True, do_recursive=True)

def convert_mtn2glb(dff_options, bon_options, mtns_path, output_path):
    # Import
    dff_importer.import_dff(dff_options)
    bpy.ops.import_scene.sth_bon(**bon_options)

    for mtn in mtns_path:
        import_sth_mtn.load(bpy.context, mtn, True)

    # Remove BON
    for o in bpy.context.scene.objects:
        if o.get("bon_model_name") is not None:
            bpy.data.objects.remove(o, do_unlink=True)

    # Remove BON actions
    for act in bpy.data.actions:
        if "baked_" not in act.name:
            bpy.data.actions.remove(act, do_unlink=True)

    # Rename baked actions
    for act in bpy.data.actions:
        act.name = act.name.replace("baked_", "")       

    # Export
    bpy.ops.export_scene.gltf(
        filepath=output_path,
        export_animations=True,
        export_materials='EXPORT'
    )
    

dff_path = "C:\\Users\\user\\Desktop\\_TARGET\\DEVILDOOM.DFF"
bon_path = "C:\\Users\\user\\Desktop\\_TARGET\\DEVILDOOM.BON"
mtn_directory = "C:\\Users\\user\\Desktop\\_TARGET\\MTN"
mtns_path = [os.path.join(mtn_directory, f) for f in os.listdir(mtn_directory) if f.endswith('.MTN')]
output_directory = mtn_directory + "\\out"
os.makedirs(output_directory, exist_ok=True)
output_path = os.path.join(output_directory, "AIO_DevilDoom.glb")

dff_options = {
    'file_name'      : dff_path,
    'image_ext'      : 'PNG',
    'connect_bones'  : False,
    'use_mat_split'  : False,
    'remove_doubles' : False,
    'group_materials': False,
    'import_normals' : True
}

bon_options = {
    'filepath'         : bon_path,
    'apply_bone_names' : True
}


cleanup()
convert_mtn2glb(dff_options, bon_options, mtns_path, output_path)

# cleanup()

```

**Comment by dreamsyntax** [comment]
> There is also no need to create NLA tracks. This code will work for the version of the addon without NLA (main branch):

Thank you! It works perfectly. I tested with the multi-mesh branch (given the models im working with) and 
Thank you for the refactor as well, that looks much cleaner than my wip script.
