### ISSUE TITLE
Bug: Simple MTNs (Squish/Scale/Rotate) for Non-Complex Objects Do Not Animate

### ISSUE THREAD

**Issue by dreamsyntax** [Psycrow101/Blender-3D-STH-Mtn-plugin#8]
Example:

weaponsResource.one -> BKGUN00CORE
--

Source (expected) result:
https://github.com/user-attachments/assets/7a87fd35-2577-4ea7-b207-603f4965f2c0

Actual result:
1.25s of animation and lots of keyframes but no visible animation change
![image](https://github.com/user-attachments/assets/31e42bdf-dfef-4f28-b271-f0e5e3bb6d8a)

(Screenshot as the inner CORE model does not shrink/expand)

Ref data:
[BKGUN00CORE.zip](https://github.com/user-attachments/files/17853343/BKGUN00CORE.zip)

**Comment by dreamsyntax** [comment]
Another example is the GOALRING object, which is just a 360 rotation animation

Expected:
https://github.com/user-attachments/assets/3732665d-8652-408a-8403-386e46a86dca

Ref data:
[goalring_res.zip](https://github.com/user-attachments/files/17853385/goalring_res.zip)

**Comment by Psycrow101** [comment]
This is a DragonFF issue for non-skinned meshes. Fixed by  https://github.com/Parik27/DragonFF/commit/113387875f4d758113f6af7ab52a6ad55508dddb

Alternative solution:
![image](https://github.com/user-attachments/assets/b2adb313-8371-4549-bbbb-5243c2f6136e)

**Comment by dreamsyntax** [comment]
Tested with the above examples.
Works great, thank you very much.
